### ISSUE TITLE
Is there an example of creating sync wrapper with a single call?

### ISSUE THREAD

**Issue by marke-apexit** [un-ts/synckit#119]
The sample in the readme involves two files.  Does synckit offer a simple function to return a synchronous version of an async function?  Something like what desync offers with `const readFile = deasync(myAsyncFn)`

**Comment by JounQin** [comment]
It can't because it requires a worker to run, if you have good idea to implement it then PR welcome.

**Comment by mmkal** [comment]
What about calling `.toString()` on the function, writing it to a temp file (with `writeFileSync`), executing as a worker like normal, getting the result, then deleting the temp file?

**Comment by JounQin** [comment]
No need, worker support plain text, but it requires seperate execution context, it may cause many unexpected behaviors which I want to avoid.
