### ISSUE TITLE
Starting with tsx does not execute correctly.

### ISSUE THREAD

**Issue by StringKe** [un-ts/synckit#122]
@JounQin 

```ts
// main.ts
import { createSyncFn, TsRunner } from 'synckit'

const syncFn = createSyncFn(require.resolve('./worker.ts'), {
    tsRunner: TsRunner.TSX,
})

syncFn(1)
```

```ts
// worker.ts
import { runAsWorker } from 'synckit'

console.log('worker started')

runAsWorker(async function main(...args) {
    console.log(args)
    return 'hello'
})
```

After starting with `yarn tsx main.ts`, work is not executed.

**Comment by JounQin** [comment]
Please provide a runnable reproduction. Maybe you want `require.resolve('./worker.js')` instead.

**Comment by StringKe** [comment]
I use `tsx`, shouldn't require a `js` file? I did not compile the `ts` file

**Comment by JounQin** [comment]
Sorry for the delay.

`require.resolve('./worker.js')` will resolve `.ts` file inside.

Do you have a reproduction if you have any issue?

**Comment by jiakun-zhao** [comment]
maybe you need install `tsx` pkg to your project.

**Comment by JounQin** [comment]
Close due to inactive.
