### ISSUE TITLE
[bug] hangs forever

### ISSUE THREAD

**Issue by loynoir** [un-ts/synckit#128]
### prepare
```
$ npm remove ts-node
$ npm exec tsc
$ ls worker.ts worker.js
worker.ts worker.js
$ grep worker runner.ts
const fn = createSyncFn(require.resolve("./worker.js"))
```

### actual
```
$ node runner.js
(hangs forever)
^C
```

### expected
```
$ npm i ts-node
$ node runner.js
OK
```

```
$ npm remove ts-node
$ mv worker.ts worker.ts.bak
$ node runner.js
OK
```

### seems like
Wrong extension priority, calling ts without tsrunner leads to syntax error.

Having no reply, so hangs forever.

**Comment by JounQin** [comment]
.ts is preferred over .js, this is intended.

**Comment by loynoir** [comment]
Hangs forever is intended, seems weird.

**Comment by loynoir** [comment]
I suggest, if no tsrunner option, don't search for ts, so it won't hangs forever.

**Comment by JounQin** [comment]
After thinking, I'll raise a fix for this. Thanks for reporting.

**Comment by JounQin** [comment]
After #141, `.ts` will still be preferred, but if there is no `ts-node` installed it will throw.
