### ISSUE TITLE
syntax errors hang server

### ISSUE THREAD

**Issue by souporserious** [un-ts/synckit#44]
Hello, thank you for this wonderful library! I'm currently using this in a Babel plugin and when testing with Jest it will hang and never complete the test if there's any sort of syntax error. Is there a way to surface these errors and kill the process if that happens? For example, you can just comment random code in `runAsWorker` and it should get stuck:

```js
runAsWorker(async () => {
 abcd
})
```

**Comment by JounQin** [comment]
@souporserious 

Hi, this is a known limitation, only error in `runAsWorker` can be caught, if hanging occurred, you can try to `SYNCKIT_TIMEOUT` env to debug, problems mostly can be fixed on development.

PR elcome to add a notice section into README.

**Comment by JounQin** [comment]
It means the content of `runAsWorker` must be valid, but you can extract logic outside.

```js
runAsWorker(async () => {
   const {} = await import('./may-have-syntax-error')
})
```

**Comment by souporserious** [comment]
Ohhh, this is brilliant! Thank you! 🎉
